/**
 * Build-time assets for the Shopify theme:
 *  1. copies every image under apps/web/public/images into theme/assets with a flat name
 *     (/images/products/the-shield/main.jpg -> cb-products-the-shield-main.jpg), WebP variants included;
 *  2. writes snippets/cb-img.liquid, a responsive <picture> renderer that knows each image's size and variants
 *     (from apps/web/src/lib/image-variants.json, produced by scripts/responsive-images.py);
 *  3. copies the self-hosted fonts from the Next build and writes assets/cb-fonts.css.liquid;
 *  4. copies favicons and brand marks.
 * Run before `tailwindcss` and `vite build`: pnpm --filter theme build.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..", "..");
const web = join(root, "apps", "web");
const theme = join(here, "..", "theme");
const assets = join(theme, "assets");
mkdirSync(assets, { recursive: true });

/** /images/products/the-shield/main.jpg -> cb-products-the-shield-main.jpg */
export const assetName = (webPath: string) => "cb-" + webPath.replace(/^\/images\//, "").replace(/\//g, "-");

// 1. images
const imagesDir = join(web, "public", "images");
let copied = 0;
const walk = (dir: string) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    if (!/\.(jpe?g|png|webp|svg)$/i.test(f)) continue;
    const webPath = "/images/" + relative(imagesDir, p).split("\\").join("/");
    const target = join(assets, assetName(webPath));
    if (!existsSync(target) || statSync(target).mtimeMs < statSync(p).mtimeMs) { copyFileSync(p, target); copied++; }
  }
};
walk(imagesDir);
console.log(`images: ${copied} copied`);

// 2. cb-img snippet
type Variant = { w: number; h: number; webp: number[] };
const manifest = JSON.parse(readFileSync(join(web, "src", "lib", "image-variants.json"), "utf8")) as Record<string, Variant>;
const cases = Object.entries(manifest)
  .map(([key, v]) => `  {%- when ${JSON.stringify(key)} -%}{%- assign cb_w = ${v.w} -%}{%- assign cb_h = ${v.h} -%}{%- assign cb_widths = "${v.webp.join(",")}" -%}`)
  .join("\n");
const snippet = `{%- comment -%}
  Responsive theme-asset image, generated by scripts/build-data.ts (do not edit).
  Usage: {% render 'cb-img', src: '/images/hero/hero-1.jpg', alt: '…', sizes: '100vw', class: 'object-[65%_center]', loading: 'eager', fetchpriority: 'high' %}
  Mirrors apps/web/src/components/Img.tsx: a <picture> with a WebP srcset when variants exist, plus intrinsic width/height.
{%- endcomment -%}
{%- liquid
  assign cb_w = nil
  assign cb_h = nil
  assign cb_widths = nil
  assign cb_sizes = sizes | default: '(min-width: 1024px) 25vw, 50vw'
  assign cb_loading = loading | default: 'lazy'
  assign cb_class = 'block h-full w-full object-cover'
  if class != blank
    assign cb_class = cb_class | append: ' ' | append: class
  endif
  assign cb_name = src | remove_first: '/images/' | replace: '/', '-' | prepend: 'cb-'
  assign cb_stem = cb_name | split: '.' | first
-%}
{%- case src -%}
${cases}
{%- endcase -%}
{%- # theme-check-disable ImgWidthAndHeight -%}
{%- capture cb_imgtag -%}<img alt="{{ alt | escape }}" src="{{ cb_name | asset_url }}" loading="{{ cb_loading }}" decoding="async"{% if fetchpriority %} fetchpriority="{{ fetchpriority }}"{% endif %}{% if cb_w %} width="{{ cb_w }}" height="{{ cb_h }}"{% endif %} class="{{ cb_class }}"{% if style %} style="{{ style }}"{% endif %}>{%- endcapture -%}
{%- # theme-check-enable ImgWidthAndHeight -%}
{%- if cb_widths -%}
{%- assign cb_list = cb_widths | split: ',' -%}
<picture class="contents"><source type="image/webp" sizes="{{ cb_sizes }}" srcset="{%- for w in cb_list -%}{{ cb_stem | append: '-' | append: w | append: '.webp' | asset_url }} {{ w }}w{%- unless forloop.last -%}, {% endunless -%}{%- endfor -%}">{{ cb_imgtag }}</picture>
{%- else -%}
{{ cb_imgtag }}
{%- endif -%}
`;
mkdirSync(join(theme, "snippets"), { recursive: true });
writeFileSync(join(theme, "snippets", "cb-img.liquid"), snippet);
console.log(`cb-img: ${Object.keys(manifest).length} images with variants`);

// 3. fonts (from the static export; the hashed files are Google's woff2 subsets, same as apps/web serves)
const cssDir = join(web, "out", "_next", "static", "css");
const mediaDir = join(web, "out", "_next", "static", "media");
if (existsSync(cssDir) && existsSync(mediaDir)) {
  const css = readdirSync(cssDir).filter((f) => f.endsWith(".css")).map((f) => readFileSync(join(cssDir, f), "utf8")).join("\n");
  const blocks = css.match(/@font-face\{[^}]*\}/g) ?? [];
  const faces: string[] = [];
  const files = new Set<string>();
  for (const b of blocks) {
    const url = b.match(/url\(([^)]+)\)/)?.[1];
    if (!url) continue;
    const file = basename(url);
    files.add(file);
    const rewritten = b.replace(/url\(([^)]+)\)/, `url({{ '${file}' | asset_url }})`).replace(/font-family:([^;]+);/, (_m, fam: string) => `font-family:${JSON.stringify(fam.trim())};`);
    if (!faces.includes(rewritten)) faces.push(rewritten);
  }
  for (const f of files) {
    const src = join(mediaDir, f);
    if (existsSync(src)) copyFileSync(src, join(assets, f));
  }
  writeFileSync(join(assets, "cb-fonts.css.liquid"), `/* Self-hosted Google font subsets (Cormorant Garamond, Jost), generated by scripts/build-data.ts */\n${faces.join("\n")}\n`);
  console.log(`fonts: ${files.size} files, ${faces.length} font-face rules`);
} else {
  console.warn("fonts: apps/web/out not found; run `pnpm --filter web build` first (keeping any previous cb-fonts.css.liquid)");
}

// 4. favicons + brand
for (const f of ["favicon.svg", "favicon.ico", "icon-192.png", "icon-512.png", "apple-touch-icon.png", "logo-badge.svg", "logo-badge-dark.svg", "logo-badge-ink.svg", "logo-mark.svg"]) {
  const src = join(web, "public", f);
  if (existsSync(src)) copyFileSync(src, join(assets, `cb-${f}`));
}
const brandDir = join(web, "public", "brand");
if (existsSync(brandDir)) for (const f of readdirSync(brandDir)) copyFileSync(join(brandDir, f), join(assets, `cb-brand-${f}`));
console.log("favicons + brand copied");
void extname;

// 5. logo badge snippet from apps/web/src/components/Store/logo-badge-paths.ts (generated by scripts/logo-badge.py)
{
  const src = readFileSync(join(web, "src", "components", "Store", "logo-badge-paths.ts"), "utf8");
  const str = (name: string) => { const m = src.match(new RegExp(`export const ${name} = '([^']*)'`)); if (!m) throw new Error(`logo-badge-paths: ${name} missing`); return m[1]; };
  const num = (name: string) => Number(src.match(new RegExp(`export const ${name} = ([0-9.]+)`))?.[1]);
  const rose = src.match(/export const ROSE = \{ cx: ([0-9.]+), cy: ([0-9.]+), r: ([0-9.]+) \}/);
  if (!rose) throw new Error("logo-badge-paths: ROSE missing");
  const liquid = `{%- comment -%}
  Crystal Basket badge (logo concept 05, palette 18). Generated by scripts/build-data.ts from logo-badge-paths.ts; do not edit.
  Usage: {% render 'cb-logo-badge', class: 'h-10 w-10', with_text: true, mono: false, title: 'Crystal Basket', attrs: 'data-class-compact ...' %}
{%- endcomment -%}
{%- liquid
  assign cb_title = title | default: 'Crystal Basket'
  if with_text == false
    assign cb_stroke = ${(num("CRYSTAL_STROKE") * 1.6).toFixed(2)}
  else
    assign cb_stroke = ${num("CRYSTAL_STROKE")}
  endif
  if mono
    assign cb_ink = 'fill-current'
    assign cb_crystal = 'currentColor'
  else
    assign cb_ink = 'fill-cb-cream'
    assign cb_crystal = 'var(--cb-cream)'
  endif
-%}
<svg viewBox="0 0 400 400" class="block{% if class != blank %} {{ class }}{% endif %}" role="img" aria-label="{{ cb_title | escape }}"{% if attrs != blank %} {{ attrs }}{% endif %}>{% unless mono %}<circle cx="200" cy="200" r="${num("DISC_R")}" class="fill-cb-rose" />{% endunless %}<g class="{{ cb_ink }}">${str("RINGS")}</g><circle cx="${rose[1]}" cy="${rose[2]}" r="${rose[3]}" class="fill-cb-gold" /><path d="${str("CRYSTAL")}" fill="none" stroke="{{ cb_crystal }}" stroke-width="{{ cb_stroke }}" stroke-linejoin="round" stroke-linecap="round" />{% unless with_text == false %}<g class="{{ cb_ink }}">${str("TEXT")}</g>{% endunless %}</svg>
`;
  writeFileSync(join(theme, "snippets", "cb-logo-badge.liquid"), liquid);
  console.log("cb-logo-badge snippet written");
}

// 6. product lifestyle photos that exist only as theme assets (Shopify products were imported with the main photo only)
{
  const productsDir = join(imagesDir, "products");
  const handles = existsSync(productsDir) ? readdirSync(productsDir).filter((h) => existsSync(join(productsDir, h, "lifestyle.jpg"))).sort() : [];
  const liquid = `{%- comment -%}
  Second product photo (on the wrist) from the theme assets, for products whose Shopify listing has only the main photo.
  Generated by scripts/build-data.ts from apps/web/public/images/products/<handle>/lifestyle.jpg; do not edit.
  Renders nothing when the product has no lifestyle photo. {% render 'cb-product-lifestyle', handle: product.handle, alt: '…', sizes: '…' %}
{%- endcomment -%}
{%- case handle -%}
${handles.map((h) => `  {%- when ${JSON.stringify(h)} -%}{%- render 'cb-img', src: '/images/products/${h}/lifestyle.jpg', alt: alt, sizes: sizes, class: class -%}`).join("\n")}
{%- endcase -%}
`;
  writeFileSync(join(theme, "snippets", "cb-product-lifestyle.liquid"), liquid);
  console.log(`cb-product-lifestyle: ${handles.length} products`);
}
